"""Standalone replacement for bookclass.py that does not require Django or spacy.

Reads the pre-built timeseries matrix and book metadata pickles that were
generated by data/build_matrix.py.

This module re-exports get_books(), get_version_str(), and get_data() with the
same signatures as the originals so the main analysis scripts can use it with
minimal changes.
"""

import os
import pickle
import numpy as np

# Resolve paths relative to this file's location
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_HERE)
DATA_DIR = os.path.join(_REPO_ROOT, "data", "gutenberg")


class Book:
    """Lightweight Book object mirroring the Django model attributes needed by the scripts."""

    def __init__(self, record: dict):
        self.pk = record["pk"]
        self.gutenberg_id = record["gutenberg_id"]
        self.title = record["title"]
        self.downloads = record["downloads"]
        self.length = record["length"]
        self.numUniqWords = record.get("numUniqWords", 0)
        self.locc_string = record.get("locc_string", "")
        self.exclude = record.get("exclude", False)

    def __str__(self):
        return self.title


def get_version_str(filters):
    P_str = "P-" if filters.get("P") else ""
    salad_str = "-salad" if filters.get("salad") else ""
    version = "{0}{1:.0f}K-{2:.0f}K-{3}dl-{4}pt{5}".format(
        P_str,
        filters["length"][0] / 1000.0,
        filters["length"][1] / 1000.0,
        filters["min_dl"],
        filters["n_points"],
        salad_str,
    )
    return version


def get_books(model_cls, filters):
    """Return a list of Book objects matching the given filters.

    The `model_cls` argument is accepted for compatibility but ignored; we
    always load from the pre-built pickle.
    """
    version = get_version_str(filters)
    books_cache = os.path.join(DATA_DIR, f"books-{version}.p")
    if not os.path.isfile(books_cache):
        raise FileNotFoundError(
            f"Book metadata cache not found: {books_cache}\n"
            f"Run  uv run python data/build_matrix.py  first."
        )
    records = pickle.load(open(books_cache, "rb"))
    return [Book(r) for r in records]


def get_data(q, version, filters, use_cache=True):
    """Return the (N_books, n_points) timeseries matrix."""
    matrix_cache = os.path.join(DATA_DIR, f"timeseries-matrix-cache-{version}.p")
    if not os.path.isfile(matrix_cache):
        raise FileNotFoundError(
            f"Matrix cache not found: {matrix_cache}\n"
            f"Run  uv run python data/build_matrix.py  first."
        )
    big_matrix = pickle.load(open(matrix_cache, "rb"))
    if big_matrix.shape[0] != len(q):
        raise ValueError(
            f"Matrix row count {big_matrix.shape[0]} != len(q) {len(q)}. "
            f"Re-run data/build_matrix.py."
        )
    return big_matrix
